name: nsp
description: A new Flutter project.

dependencies:
  cupertino_icons: ^0.1.2
  json_annotation: ^0.2.3
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner: ^0.9.0
  json_serializable: ^0.5.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true